import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import ContactForm from '../components/ContactForm';

export const metadata: Metadata = {
  title: 'Espejo Software | Aplicaciones web y móviles a medida',
  description: 'Estudio de software en Florida que crea y administra aplicaciones web y móviles para empresas.',
  alternates: { canonical: '/es', languages: { 'en-US': '/', 'es-US': '/es' } },
  openGraph: { title: 'Espejo Software | Convertimos tu idea en software', description: 'Aplicaciones web, aplicaciones móviles y soporte continuo para empresas y emprendedores.', url: '/es', locale: 'es_US' },
};

const services = [
  { number: '01', title: 'Aplicaciones web', text: 'Plataformas a medida, diseñadas alrededor de tus operaciones, clientes y próxima etapa de crecimiento.', example: 'TradeWork', detail: 'Operaciones · CRM · Portales para clientes', image: '/tradework-portfolio.png', href: '/es/work/tradework' },
  { number: '02', title: 'Productos móviles', text: 'Experiencias móviles claras y confiables que mantienen a tu empresa cerca de sus clientes.', example: 'TAG Groceries', detail: 'iOS y Android · Herramientas compartidas · UX móvil', image: '/tag-portfolio.png', href: '/es/work/tag-groceries' },
  { number: '03', title: 'Gestión de aplicaciones', text: 'Mejoras continuas, monitoreo y soporte de un socio que conoce tu producto.', example: 'Elite Driving School', detail: 'Monitoreo · Mejoras · Soporte continuo', image: '/elite-dashboard.png', href: '/es/work/elite-driving-school' },
];

const projects = [
  { name: 'TradeWork', slug: 'tradework', label: 'Operaciones · Web + móvil', text: 'Una plataforma creada para que empresas de servicios organicen solicitudes, trabajos, equipos y clientes.', href: 'https://app.tradeworkapp.com', image: '/tradework-portfolio.png', className: 'wide' },
  { name: 'Elite Driving School', slug: 'elite-driving-school', label: 'Programación y portal · Aplicación web', text: 'Una experiencia completa para inscripciones, horarios, pagos, documentos y seguimiento del progreso estudiantil.', href: 'https://elitedriversmn.com', image: '/elite-portfolio.png', className: 'tall' },
  { name: 'TAG Groceries', slug: 'tag-groceries', label: 'Compras · Aplicación móvil', text: 'Una aplicación práctica que organiza listas de compras por tienda, pasillo o cualquier etiqueta personalizada.', href: 'https://taggroceries.com/#/', image: '/tag-portfolio.png', className: 'phone' },
];

const pricing = [
  { label: 'Soporte flexible', name: 'Por hora', price: '$80', cadence: 'por hora', text: 'Desarrollo, consultoría, solución de problemas o mejoras puntuales cuando necesitas experiencia adicional.', note: 'Paga solamente por el tiempo utilizado' },
  { label: 'Colaboración mensual', name: 'Impulso', price: '$650', cadence: 'por mes', text: 'Diez horas dedicadas cada mes para mejoras, mantenimiento y progreso constante de tu producto.', note: 'Incluye hasta 10 horas' },
  { label: 'Colaboración mensual', name: 'Crecimiento', price: '$1,400', cadence: 'por mes', text: 'Veinticinco horas dedicadas para empresas con una hoja de ruta activa y desarrollo continuo.', note: 'Incluye hasta 25 horas' },
  { label: 'Presencia web sencilla', name: 'Sitio web estático', price: '$500', cadence: 'desde', text: 'Un sitio web profesional y adaptable que presenta tu negocio y guía a los visitantes hacia el próximo paso.', note: 'Ideal para sitios informativos enfocados' },
  { label: 'Convierte la idea en algo real', name: 'MVP', price: '$5,000', cadence: 'desde', text: 'Lanza la versión esencial de tu aplicación web o móvil, ponla en manos de usuarios y descubre qué crear después.', note: 'Alcance enfocado · Producto real · Listo para probar', featured: true },
  { label: 'Creada alrededor de tu empresa', name: 'Aplicación a medida', price: '$10,000', cadence: 'desde', text: 'Una aplicación completa diseñada alrededor de tus clientes, procesos y objetivos. El alcance confirma la inversión final.', note: 'Web o móvil · Requiere definir el alcance' },
];

export default function SpanishHome() {
  return <main>
    <nav className="nav shell" aria-label="Navegación principal"><a className="brand" href="#top" aria-label="Inicio de Espejo Software"><span>E</span> ESPEJO SOFTWARE</a><div className="nav-links"><a href="#services">Servicios</a><a href="#work">Proyectos</a><a href="#pricing">Precios</a><a href="#about">Nosotros</a></div><Link className="lang-switch" href="/" lang="en">EN</Link><a className="outline-button" href="#contact">Inicia un proyecto ↗</a></nav>

    <section className="idea-story" id="top"><div className="shell idea-story-inner">
      <div className="idea-story-heading"><p className="eyebrow">Estudio de software independiente · Florida</p><h1>¿Tienes una idea?<br /><em>Hagámosla realidad.</em></h1></div>
      <div className="idea-story-copy"><p className="idea-story-lede">Quizás empieza con algo sencillo: <strong>“Ojalá mis clientes pudieran…”</strong> o <strong>“Tiene que haber una mejor manera de hacer esto.”</strong> Eso es suficiente para comenzar.</p><p>No necesitas un plan técnico ni todas las respuestas. Trae el problema, la oportunidad o incluso ese ambicioso “¿qué pasaría si…?”. Juntos lo convertiremos en software que las personas puedan usar, probar y mejorar.</p><div className="idea-actions"><a className="idea-button" href="#contact">Cuéntame tu idea ↗</a><a href="#work">Mira lo que es posible ↓</a></div></div>
      <div className="idea-path" aria-label="Cómo una idea se convierte en software"><article><span>01</span><h3>Imagina</h3><p>Visualiza qué podría ser más fácil, rápido o completamente nuevo para tu empresa y tus clientes.</p></article><article><span>02</span><h3>Define</h3><p>Convertimos la visión en un plan enfocado, priorizando primero lo que genera mayor valor.</p></article><article><span>03</span><h3>Crea</h3><p>Tu idea se convierte en un producto útil, confiable y preparado para crecer en el mundo real.</p></article></div>
    </div></section>

    <section className="service-strip" id="services"><div className="shell service-grid">{services.map((service) => <article className="service-card" key={service.number}><div className="service-copy"><small>{service.number} / SERVICIO</small><h2>{service.title}</h2><p>{service.text}</p></div><a className="service-example" href={service.href} aria-label={`Ver el proyecto ${service.example}`}><span className="service-visual"><Image src={service.image} alt={`Ejemplo de la aplicación ${service.example}`} fill sizes="(max-width: 650px) 100vw, 33vw" /></span><span className="service-example-copy"><small>EJEMPLO / {service.example}</small><b>{service.detail}</b><i>Ver el proyecto →</i></span></a></article>)}</div></section>

    <section className="work shell" id="work"><div className="section-title"><div><p className="eyebrow">Proyectos seleccionados</p><h2>Creado para<br /><em>el mundo real.</em></h2></div><p>Software que ya ayuda a empresas a atender clientes, administrar operaciones y seguir avanzando.</p></div><div className="project-list">{projects.map((project, index) => <article className={`project ${project.className}`} key={project.name}><div className="project-meta"><small>0{index + 1} / {project.label}</small><h3>{project.name}</h3><p>{project.text}</p><div className="project-links"><a href={`/es/work/${project.slug}`}>Ver el proyecto →</a><a href={project.href} target="_blank" rel="noreferrer">Visitar ↗</a></div></div><a className="project-image" href={`/es/work/${project.slug}`} aria-label={`Ver el proyecto ${project.name}`}><Image src={project.image} alt={`Interfaz de ${project.name}`} fill sizes="(max-width: 800px) 100vw, 62vw" /></a></article>)}</div></section>

    <section className="pricing" id="pricing"><div className="shell"><div className="pricing-heading"><div><p className="eyebrow">Formas de trabajar juntos</p><h2>Tú haces lo que mejor sabes hacer.<br /><em>Yo crearé lo que viene.</em></h2></div><div><p>Tú tienes la visión y el conocimiento de tu negocio. Yo aporto años de experiencia convirtiendo ideas en software útil, desde MVPs enfocados hasta aplicaciones web y móviles completas.</p><p>Empieza poco a poco, mantén el impulso cada mes o crea ese producto que llevas tiempo imaginando.</p></div></div><div className="pricing-grid">{pricing.map((plan) => <article className={plan.featured ? 'pricing-card featured' : 'pricing-card'} key={plan.name}>{plan.featured && <span className="featured-badge">EMPIEZA AQUÍ</span>}<small>{plan.label}</small><h3>{plan.name}</h3><div className="price"><strong>{plan.price}</strong><span>{plan.cadence}</span></div><p>{plan.text}</p><div className="pricing-note">{plan.note}</div><a href="#contact">Hablemos ↗</a></article>)}</div><div className="pricing-footer"><p>Cada proyecto comienza con una conversación. Confirmamos el precio final, el alcance y el calendario antes de comenzar.</p><a href="#contact">Cuéntame qué estás imaginando →</a></div></div></section>

    <section className="about" id="about"><div className="shell"><div className="about-heading"><p className="eyebrow">Conoce al fundador</p><h2>Experiencia a gran escala.<br /><em>Creado para personas reales.</em></h2></div><div className="founder-grid"><div className="founder-photo"><Image src="/carlos-espejo.jpg" alt="Carlos Espejo después de completar un maratón" fill sizes="(max-width: 800px) 100vw, 45vw" /></div><div className="founder-story"><p className="founder-name">Carlos Espejo <span>Fundador y desarrollador de software</span></p><p>He pasado años creando software en entornos muy distintos, desde grandes empresas como Target y Entrust hasta proyectos de consultoría y productos personalizados para pequeñas empresas. Esa variedad me enseñó a aplicar una perspectiva empresarial a problemas prácticos sin hacer la solución más complicada de lo necesario.</p><p>Como desarrollador y emprendedor, me apasiona entender cómo funciona algo, descubrir dónde se detiene y crear un mejor camino. El software es una de las mejores herramientas que conozco para conectar personas, simplificar el trabajo y convertir una idea en algo verdaderamente útil.</p><p>Fuera del trabajo, soy un hombre de familia que disfruta pasar tiempo con familiares y amigos. También me encontrarás jugando baloncesto o corriendo. La disciplina, el trabajo en equipo, el progreso constante y disfrutar el proceso también guían mi manera de trabajar.</p><div className="founder-quote">“El mejor software no presume de su complejidad. Simplemente hace que el trabajo sea más fácil.”</div></div></div><div className="principles"><span><b>EXPERIENCIA</b>Perspectiva empresarial con ejecución práctica.</span><span><b>PRÁCTICO</b>Tecnología diseñada alrededor del problema real.</span><span><b>PERSONAL</b>Colaboración directa desde la idea hasta el lanzamiento.</span></div></div></section>

    <section className="contact" id="contact"><div className="shell contact-grid"><div className="contact-intro"><p className="eyebrow">Inicia un proyecto</p><h2>¿Qué podría funcionar<br /><em>mejor?</em></h2><p>Cuéntanos qué está frenando a tu empresa o qué te gustaría que pudiera hacer tu software. Comenzaremos con una conversación enfocada.</p><a href="mailto:cespejo1@yahoo.com">cespejo1@yahoo.com ↗</a></div><ContactForm locale="es" /></div></section>
    <footer className="footer shell"><a className="brand" href="#top"><span>E</span> ESPEJO SOFTWARE</a><p>Aplicaciones web · Aplicaciones móviles · Soporte continuo</p><div><span>© {new Date().getFullYear()} Espejo Software LLC</span><span>Florida, EE. UU.</span></div></footer>
  </main>;
}
